### ISSUE TITLE
[REQ] Qbittorrent dark theme different icon colors for stalled up/download

### ISSUE THREAD

**Issue by mzso** [MahdyMirzade/Dotfiles#1]
Hi!
I got here via list of themes from the QBs repository. I was wondering whether you plan on enhancements to the theme?

My main annoyance is that the stall up and downloads are the same color which makes it rather hard to tell them apart.

Also (I don't have high hopes for this) I wonder if you would consider other color variants of the theme. I rather prefer warm hues, especially on a dark theme instead of blue.

**Comment by MahdiMirzadeh** [comment]
Hello mzso, Sorry for the late reply.

I updated the theme, it now has better icon pack and WebUI support. You can find this theme on its [new repository](https://github.com/MahdiMirzade/qbittorrent) now. I don't think I'll update the theme in this repository ever again and my next push to my personal dotfiles will delete it.

> My main annoyance is that the stall up and downloads are the same color which makes it rather hard to tell them apart.

It might be the theme update, but stalled uploading and downloading colors are completely different, will [the new .qbtheme file](https://github.com/dracula/qbittorrent/raw/master/qbittorrent.qbtheme) fix it?
![image](https://user-images.githubusercontent.com/63877463/160243763-34bcf7fa-c363-46fa-861f-07c9f624f1ba.png)
If you want to make changes to the the theme you can create a PR on the new repository with screenshots. 

> Also (I don't have high hopes for this) I wonder if you would consider other color variants of the theme. I rather prefer warm hues, especially on a dark theme instead of blue.

That is actually something I've been working on some months ago, but not designing new variants but generating them. Basically I want to generate the .qss files using my .Xresources and create qbittorrent themes from them. (gruvbox-dark, nord, oceanic-next, onedark, etc)
I got lost in the design and generating new variants process that I left the project, I might get back to it soon and will update you in this issue. (no promises)

Best Regards, Mahdi

**Comment by mzso** [comment]
@MahdiMirzade 
Hi!
The stalled up a downloads are still identically colored. Also shown on your preview:
![kép](https://user-images.githubusercontent.com/4479090/160247902-9c4c6ad5-c7e4-4adc-8f8c-95cf82c7bc16.png)
Every other status seems to have a unique color.

**Comment by MahdiMirzadeh** [comment]
I played with the SVGs a little bit and came up with something like this, I'm not really good with coloring but I think this is better than before, I updated the icons at https://github.com/MahdiMirzade/qbittorrent/commit/d2e216d271779bc21b6ad29fcb89a492a76e214e .
Would this fix it?

![image](https://user-images.githubusercontent.com/63877463/160249444-f50a91b0-a1ea-4128-9513-762fd1ffc4c8.png)

**Comment by mzso** [comment]
[**@MahdiMirzade**](https://github.com/MahdiMirzade) commented on [2022. márc. 26. 17:54 CET](https://github.com/MahdiMirzade/Dotfiles/issues/1#issuecomment-1079732079 "2022-03-26T16:54:40Z - Replied by Github Reply Comments"):
> I played with the SVGs a little bit and came up with something like this, I'm not really good with coloring but I think this is better than before, I updated the icons at [MahdiMirzade/qbittorrent@d2e216d](https://github.com/MahdiMirzade/qbittorrent/commit/d2e216d271779bc21b6ad29fcb89a492a76e214e) .  
> Would this fix it?
> 
> [![image](https://user-images.githubusercontent.com/63877463/160249444-f50a91b0-a1ea-4128-9513-762fd1ffc4c8.png)](https://user-images.githubusercontent.com/63877463/160249444-f50a91b0-a1ea-4128-9513-762fd1ffc4c8.png)

It's certainly different now. I think the "Stalled download" should be less saturated than "Downloading" otherwise it might get confusing.
Maybe something like this?
![kép](https://user-images.githubusercontent.com/4479090/160255056-755650ed-49ea-490e-908e-b19a88c54056.png)

(I'm not good with colors either...)

**Comment by MahdiMirzadeh** [comment]
> It's certainly different now. I think the "Stalled download" should be less saturated than "Downloading" otherwise it might get confusing.

I agree, but I was worried that it would be too bright and turn out wierd.

> Maybe something like this?

I played a little bit more, and this is something I thought might just pass the test:
![image](https://user-images.githubusercontent.com/63877463/160267157-e5166a26-7ab4-4d72-a4a8-5ee77fb8dbe8.png)
Would this do? (It's not pushed to the repo yet)

**Comment by mzso** [comment]
@MahdiMirzade 
>  I was worried that it would be too bright and turn out wierd.

Not sure what you mean by that.

> 
> I played a little bit more, and this is something I thought might just pass the test:
> 
> Would this do? (It's not pushed to the repo yet)

Fine by me. I suggested a more faded color thinking it would be less confusable with the "downloading" state.

**Comment by MahdiMirzadeh** [comment]
> Fine by me. I suggested a more faded color thinking it would be less confusable with the "downloading" state.

Pushed to the repo on https://github.com/MahdiMirzade/qbittorrent/commit/db5a48843a454cb1df0f51ef2fe1118dd00626d8, you can now download the new [.qbtheme theme file](https://github.com/MahdiMirzade/qbittorrent/raw/master/qbittorrent.qbtheme).
Also if it turned out to met your expectations, you can close this issue.

Kind Regards, Mahdi

**Comment by mzso** [comment]
[**@MahdiMirzade**](https://github.com/MahdiMirzade) commented on [2022. márc. 29. 22:14 CEST](https://github.com/MahdiMirzade/Dotfiles/issues/1#issuecomment-1082331104 "2022-03-29T20:14:26Z - Replied by Github Reply Comments"):
> > Fine by me. I suggested a more faded color thinking it would be less confusable with the "downloading" state.
> 
> Pushed to the repo on [MahdiMirzade/qbittorrent@db5a488](https://github.com/MahdiMirzade/qbittorrent/commit/db5a48843a454cb1df0f51ef2fe1118dd00626d8), you can now download the new [.qbtheme theme file](https://github.com/MahdiMirzade/qbittorrent/raw/master/qbittorrent.qbtheme).  
> Also if it turned out to met your expectations, you can close this issue.
> 
> Kind Regards, Mahdi

Thanks!
